// Generated by LiveScript 1.2.0
window.requestAnimationFrame = function(){
  return window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback){
    console.log("browser not suport requestAnimationFrame");
    return window.setTimeout(callback, 1000 / 60);
  };
}();



(function(window, undefined){

	var _ctx; 
	var _width; 
	var _height;
	var _el;
	var _squares = [];   
	var _step;
	var _frame = 0;
	var _getSquare = function(px, py){
		if(_squares[px] == null){
			_squares[px] = []; 
		}
		return _squares[px][py]; 

	}
	var _setSquare = function(px, py, value){
		if(_squares[px] == null){
			_squares[px] = []; 
		}
		return _squares[px][py] = value; 

	}
	var _countVoisin = function(posAround){
		var count = 0;
		posAround.forEach(function(pos){
			
			if (_squares[pos.x][pos.y] && _squares[pos.x][pos.y].alive) {

				count++;
			}
			// debugger;
		});
		return count;
	}
	var _getAround = function(obj, x, y){
		var posAround = [
			{x: x-1, y: y - 1},
			{x: x,   y: y-1},
			{x: x+1, y: y - 1},
			
			{x: x-1, y: y},
			{x: x+1, y: y},
			
			{x: x-1, y: y+1},
			{x: x,   y: y+1},
			{x: x+1, y: y+1}

		];

		var truePosAround = [];
		posAround.forEach(function(pos){
			if (pos.x >= 0 && pos.y >= 0){
				truePosAround.push(pos);
			}
		})

		var voisin = _countVoisin(truePosAround);
		// console.log(voisin);
		if (obj.alive === false && voisin === 3) { 
			obj.alive = true;
		} else if (!(obj.alive && (voisin == 2) || (voisin == 3) )) {
			obj.alive = false;
		}

	}
	window.Conway = function(o){
		if(o == null) o = {};
		_el = document.createElement("canvas");
		_width  = o.width||400; 
		_height = o.height||400;
		_ctx = _el.getContext("2d"); 
		_el.width = _width; 
		_el.height = _height;
		_step = _height/10;
		for (var i = 0; i < _step; i++){
			_squares[i] = []
			for(var j= 0; j < _step; j++) {
				_squares[i][j] = {color: "red", alive: false}
			}
		}
	}
	Conway.prototype.draw = function(){
		_frame++;
		_ctx.clearRect(0,0, _height, _width)

		_ctx.fillStyle = "#fff5df";
		_ctx.fillRect(0,0, _height, _width); 

	

		if (_frame % 4 == 0) {

			_squares.forEach(function(px, i){
				px.forEach(function(obj, j){
					_getAround(obj, i, j)
				})
			})

		}

		if(clicked){
			_setSquare(Math.floor(mouseX/10), Math.floor(mouseY/10), { color : "red", alive : true });
		}


		_squares.forEach(function(px, i){
			px.forEach(function(obj, j){
				if(obj && obj.alive){
					_ctx.fillStyle = obj.color;
					_ctx.fillRect(i*10,j*10,10, 10);
				}
			})
		})


	}
	Conway.prototype.drawLine = function(bx, by, ex, ey){
		_ctx.beginPath(); 
		_ctx.moveTo(bx, by); 
		_ctx.lineTo(ex, ey); 
		_ctx.closePath(); 
		_ctx.stroke(); 	
	}
	Conway.prototype.getHeight= function(){
		return _height; 
	}
	Conway.prototype.getCanvas = function(){
		return _el; 
	}

}(window))



var mouseX; 
var mouseY; 
var clicked = false; 

document.addEventListener("mousedown", function(ev){
	clicked = true; 
	mouseX = ev.x 
	mouseY = ev.y 
}); 
document.addEventListener("mouseup", function(){
	clicked = false; 
}); 
document.addEventListener("mousemove", function(ev){
		mouseX = ev.x 
		mouseY = ev.y 
});


var jeu = new Conway({});
document.body.appendChild(jeu.getCanvas()); 






draw = function draw() {
	requestAnimationFrame(draw)
	jeu.draw(); 
}

draw()




















